config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :gifs

  root to: "gifs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/gif.rb
class Gif < ApplicationRecord
  include ImageUploader::Attachment(:image)
  belongs_to :user
  acts_as_taggable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_person_name

  has_many :gifs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_gif, only: [:edit, :update, :destroy]

  # GET /gifs
  # GET /gifs.json
  def index
    @gifs = Gif.all
  end

  # GET /gifs/1
  # GET /gifs/1.json
  def show
    @gif = Gif.find(params[:id])
  end

  # GET /gifs/new
  def new
    @gif = Gif.new
  end

  # GET /gifs/1/edit
  def edit
  end

  # POST /gifs
  # POST /gifs.json
  def create
    @gif = current_user.gifs.new(gif_params)

    respond_to do |format|
      if @gif.save
        format.html { redirect_to @gif, notice: 'Gif was successfully created.' }
        format.json { render :show, status: :created, location: @gif }
      else
        format.html { render :new }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gifs/1
  # PATCH/PUT /gifs/1.json
  def update
    respond_to do |format|
      if @gif.update(gif_params)
        format.html { redirect_to @gif, notice: 'Gif was successfully updated.' }
        format.json { render :show, status: :ok, location: @gif }
      else
        format.html { render :edit }
        format.json { render json: @gif.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifs/1
  # DELETE /gifs/1.json
  def destroy
    @gif.destroy
    respond_to do |format|
      format.html { redirect_to gifs_url, notice: 'Gif was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gif
      @gif = current_user.gifs.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gif_params
      params.require(:gif).permit(:image, :tag_list)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gifs_helper.rb
module GifsHelper
  def linked_tag_list(gif)
    list = gif.tag_list.map do |tag_name|
      link_to tag_name, root_path(tag: tag_name) 
    end

    safe_join list, ", "
  end
end

app/views/gifs/_form.html.erb
<%= form_with(model: gif, local: true) do |form| %>
  <% if gif.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gif.errors.count, "error") %> prohibited this gif from being saved:</h2>

      <ul>
        <% gif.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :image %>
    <%= form.hidden_field :image, value: form.object.cached_image_data %>
    <%= form.file_field :image %>
  </div>


  <div class="field">
    <%= form.label :tag_list %>
    <%= form.text_field :tag_list, value: form.object.tag_list.join(", ") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gifs/edit.html.erb
<h1>Editing Gif</h1>

<%= render 'form', gif: @gif %>

<%= link_to 'Destroy', gif, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Show', @gif %> |
<%= link_to 'Back', gifs_path %>

app/views/gifs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gifs</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Image data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifs.each do |gif| %>
      <tr>
        <td><%= gif.user_id %></td>
        <td><%= gif.image_data %></td>
        <td><%= link_to 'Show', gif %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gif', new_gif_path %>

app/views/gifs/new.html.erb
<h1>New Gif</h1>

<%= render 'form', gif: @gif %>

<%= link_to 'Back', gifs_path %>

app/views/gifs/show.html.erb
<p id="notice"><%= notice %></p>
  
<%= image_tag @gif.image_url %>

<p>Uploaded by: <%= @gif.user.name %> </p>

<p><%= linked_tag_list @gif %></p>

<% if user_signed_in? && current_user == @gif.user %> 
  <%= link_to 'Edit', edit_gif_path(@gif) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimatedgifMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.11.2/css/all.css">
  </head>

  <body>

    <%= render "shared/navbar" %>

    
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="fixed z-100 bg-gray-100 inset-x-0 top-0 border-b-2 border-gray-200 lg:border-b-0 lg:static flex items-center">
        <div class="w-full max-w-screen-xl relative mx-auto px-6">
          <div class="lg:border-b-2 lg:border-gray-200 h-24 flex flex-col justify-center">
            <div class="flex items-center -mx-6">

              
              <div class="lg:w-1/4 xl:w-1/5 pl-6 pr-6">
                <div class="flex items-center">
                  <a href="/web/20200326074939/https://tailwindcss.com/" class="block"> AnimatedGif.me</a>
                </div>
              </div>

              <div class="flex flex-grow lg:w-3/4 xl:w-4/5">
                
                <div class="hidden lg:flex lg:items-center lg:justify-between xl:w-1/4 px-6">

                  <div class="flex justify-start items-center text-gray-500">
                    <a class="block flex items-center hover:text-gray-700 mr-5" href="https://web.archive.org/web/20200326074939/https://github.com/tailwindcss/tailwindcss">
                      <svg class="fill-current w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>GitHub</title><path d="M10 0a10 10 0 0 0-3.16 19.49c.5.1.68-.22.68-.48l-.01-1.7c-2.78.6-3.37-1.34-3.37-1.34-.46-1.16-1.11-1.47-1.11-1.47-.9-.62.07-.6.07-.6 1 .07 1.53 1.03 1.53 1.03.9 1.52 2.34 1.08 2.91.83.1-.65.35-1.09.63-1.34-2.22-.25-4.55-1.11-4.55-4.94 0-1.1.39-1.99 1.03-2.69a3.6 3.6 0 0 1 .1-2.64s.84-.27 2.75 1.02a9.58 9.58 0 0 1 5 0c1.91-1.3 2.75-1.02 2.75-1.02.55 1.37.2 2.4.1 2.64.64.7 1.03 1.6 1.03 2.69 0 3.84-2.34 4.68-4.57 4.93.36.31.68.92.68 1.85l-.01 2.75c0 .26.18.58.69.48A10 10 0 0 0 10 0"></path></svg>
                    </a>
                    <a class="block flex items-center hover:text-gray-700 mr-5" href="https://web.archive.org/web/20200326074939/https://twitter.com/tailwindcss">
                      <svg class="fill-current w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><title>Twitter</title><path d="M6.29 18.25c7.55 0 11.67-6.25 11.67-11.67v-.53c.8-.59 1.49-1.3 2.04-2.13-.75.33-1.54.55-2.36.65a4.12 4.12 0 0 0 1.8-2.27c-.8.48-1.68.81-2.6 1a4.1 4.1 0 0 0-7 3.74 11.65 11.65 0 0 1-8.45-4.3 4.1 4.1 0 0 0 1.27 5.49C2.01 8.2 1.37 8.03.8 7.7v.05a4.1 4.1 0 0 0 3.3 4.03 4.1 4.1 0 0 1-1.86.07 4.1 4.1 0 0 0 3.83 2.85A8.23 8.23 0 0 1 0 16.4a11.62 11.62 0 0 0 6.29 1.84"></path></svg>
                    </a>
                    <a class="block flex items-center hover:text-gray-700" href="/web/20200326074939/https://tailwindcss.com/discord">
                      <svg class="fill-current w-5 h-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 146 146"><title>Discord</title><path d="M107.75 125.001s-4.5-5.375-8.25-10.125c16.375-4.625 22.625-14.875 22.625-14.875-5.125 3.375-10 5.75-14.375 7.375-6.25 2.625-12.25 4.375-18.125 5.375-12 2.25-23 1.625-32.375-.125-7.125-1.375-13.25-3.375-18.375-5.375-2.875-1.125-6-2.5-9.125-4.25-.375-.25-.75-.375-1.125-.625-.25-.125-.375-.25-.5-.375-2.25-1.25-3.5-2.125-3.5-2.125s6 10 21.875 14.75c-3.75 4.75-8.375 10.375-8.375 10.375-27.625-.875-38.125-19-38.125-19 0-40.25 18-72.875 18-72.875 18-13.5 35.125-13.125 35.125-13.125l1.25 1.5c-22.5 6.5-32.875 16.375-32.875 16.375s2.75-1.5 7.375-3.625c13.375-5.875 24-7.5 28.375-7.875.75-.125 1.375-.25 2.125-.25 7.625-1 16.25-1.25 25.25-.25 11.875 1.375 24.625 4.875 37.625 12 0 0-9.875-9.375-31.125-15.875l1.75-2S110 19.626 128 33.126c0 0 18 32.625 18 72.875 0 0-10.625 18.125-38.25 19zM49.625 66.626c-7.125 0-12.75 6.25-12.75 13.875s5.75 13.875 12.75 13.875c7.125 0 12.75-6.25 12.75-13.875.125-7.625-5.625-13.875-12.75-13.875zm45.625 0c-7.125 0-12.75 6.25-12.75 13.875s5.75 13.875 12.75 13.875c7.125 0 12.75-6.25 12.75-13.875s-5.625-13.875-12.75-13.875z" fill-rule="nonzero"></path></svg>
                    </a>
                  </div>
                </div>
              </div>


            </div>
          </div>
        </div>
      </div>  

<p>
      <%= link_to "Gifs", root_path %>
      <% if user_signed_in? %>
        <%= link_to "Account", edit_user_registration_path %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %>
        <%= link_to "Sign in", new_user_session_path %>
      <% end %>
    </p> 